"""add executed by to execution records

Revision ID: 1c38d9bfd5e9
Revises: ee7519ed8b13
Create Date: 2026-09-18 22:20:46.729744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c38d9bfd5e9'
down_revision: Union[str, Sequence[str], None] = 'ee7519ed8b13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('execution_records', sa.Column('executed_by', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_execution_records_executed_by'), 'execution_records', ['executed_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_execution_records_executed_by'), table_name='execution_records')
    op.drop_column('execution_records', 'executed_by')
    # ### end Alembic commands ###
