"""add approval requests table

Revision ID: 4ca68c5c789a
Revises: 7461d28569d5
Create Date: 2026-09-12 10:04:25.816293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ca68c5c789a'
down_revision: Union[str, Sequence[str], None] = '7461d28569d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_requests',
    sa.Column('approval_id', sa.String(length=36), nullable=False),
    sa.Column('action_name', sa.String(length=100), nullable=False),
    sa.Column('action_risk', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('requested_by', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('reviewer', sa.String(length=100), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('approval_id')
    )
    op.create_index(op.f('ix_approval_requests_action_name'), 'approval_requests', ['action_name'], unique=False)
    op.create_index(op.f('ix_approval_requests_status'), 'approval_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approval_requests_status'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_action_name'), table_name='approval_requests')
    op.drop_table('approval_requests')
    # ### end Alembic commands ###
