"""upgrade pipeline runs schema

Revision ID: 7461d28569d5
Revises: 
Create Date: 2026-09-11 12:12:57.521062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7461d28569d5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=100), nullable=False),
    sa.Column('pipeline_name', sa.String(length=255), nullable=False),
    sa.Column('business_domain', sa.String(length=100), nullable=False),
    sa.Column('environment', sa.String(length=50), nullable=False),
    sa.Column('source_system', sa.String(length=255), nullable=False),
    sa.Column('target_system', sa.String(length=255), nullable=False),
    sa.Column('orchestrator', sa.String(length=100), nullable=False),
    sa.Column('job_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('records_read', sa.Integer(), nullable=False),
    sa.Column('records_written', sa.Integer(), nullable=False),
    sa.Column('records_rejected', sa.Integer(), nullable=False),
    sa.Column('data_quality_status', sa.String(length=50), nullable=False),
    sa.Column('sla_seconds', sa.Integer(), nullable=False),
    sa.Column('sla_breach_seconds', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_category', sa.String(length=100), nullable=True),
    sa.Column('owner_team', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('correlation_id', sa.String(length=150), nullable=False),
    sa.Column('incident_id', sa.String(length=100), nullable=True),
    sa.Column('recovery_action', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_runs_correlation_id'), 'pipeline_runs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_error_category'), 'pipeline_runs', ['error_category'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_incident_id'), 'pipeline_runs', ['incident_id'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_pipeline_name'), 'pipeline_runs', ['pipeline_name'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_run_id'), 'pipeline_runs', ['run_id'], unique=True)
    op.create_index(op.f('ix_pipeline_runs_status'), 'pipeline_runs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_runs_status'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_run_id'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_pipeline_name'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_incident_id'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_error_category'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_correlation_id'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    # ### end Alembic commands ###
