"""add approval resource fields

Revision ID: c1b38e6ecc65
Revises: 4ca68c5c789a
Create Date: 2026-09-14 13:58:01.747543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1b38e6ecc65'
down_revision: Union[str, Sequence[str], None] = '4ca68c5c789a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approval_requests', sa.Column('resource_type', sa.String(length=50), nullable=True))
    op.add_column('approval_requests', sa.Column('resource_name', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_approval_requests_resource_name'), 'approval_requests', ['resource_name'], unique=False)
    op.create_index(op.f('ix_approval_requests_resource_type'), 'approval_requests', ['resource_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approval_requests_resource_type'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_resource_name'), table_name='approval_requests')
    op.drop_column('approval_requests', 'resource_name')
    op.drop_column('approval_requests', 'resource_type')
    # ### end Alembic commands ###
