"""add execution records table

Revision ID: ee7519ed8b13
Revises: c1b38e6ecc65
Create Date: 2026-09-15 12:20:01.747582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee7519ed8b13'
down_revision: Union[str, Sequence[str], None] = 'c1b38e6ecc65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_records',
    sa.Column('execution_id', sa.String(length=36), nullable=False),
    sa.Column('approval_id', sa.String(length=36), nullable=False),
    sa.Column('action_name', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_name', sa.String(length=255), nullable=False),
    sa.Column('executor_provider', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('execution_id')
    )
    op.create_index(op.f('ix_execution_records_action_name'), 'execution_records', ['action_name'], unique=False)
    op.create_index(op.f('ix_execution_records_approval_id'), 'execution_records', ['approval_id'], unique=True)
    op.create_index(op.f('ix_execution_records_status'), 'execution_records', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_execution_records_status'), table_name='execution_records')
    op.drop_index(op.f('ix_execution_records_approval_id'), table_name='execution_records')
    op.drop_index(op.f('ix_execution_records_action_name'), table_name='execution_records')
    op.drop_table('execution_records')
    # ### end Alembic commands ###
